#
# z position is relative to the detector center
# Center wire id is zero-origin.
# Angle is defined so that the coordinate system is the right-handed system.
#
# The angle of axis of each plane to the horizontal axis.

- x1: #X1
    z:         +7.5
    nWire:    &nwire  16
    cellSize: &cell   5.
    angle:    &xangle 0.
    center:    9.
#    center:    8.841
#    center:    7.7818
#   center:    6.701
- x2: #X1'
    z:         +2.7
    nWire:    *nwire
    cellSize: *cell
    angle:    *xangle
    center:    8.5
#    center:    8.365
#    center:    6.247
- y1: #Y1
    z:         -2.1
    nWire:    *nwire
    cellSize: *cell
    angle:    &yangle 90.
    center:    9
#    center:    7.578
#    center:    6.714
- y2: #Y1'
    z:         -6.9
    nWire:    *nwire
    cellSize: *cell
    angle:    *yangle
    center:    8.5
#    center:    7.115
#    center:    6.278
